name: GitHub Actions Demo
on: [push]
jobs:
  test:
   runs-on: ubuntu-latest
   steps:
     - name: Check out repository code - test
       uses: actions/checkout@v2
     - run: mvn test
 
  buildAndDeploy:
      runs-on: ubuntu-latest
      steps:
        - name: build
          uses: actions/checkout@v2
        - run : mvn package
        - name: deploy  
          uses: kielabokkie/ssh-key-and-known-hosts-action@v1
          with:
            ssh-private-key: ${{ secrets.SSHPETCLINIC }}
            ssh-host: cda.cefim-formation.org
        - run: ssh-keyscan -H cda.cefim-formation.org >> ~/.ssh/known_hosts
        - run: |
            scp ./target/spring-petclinic-2.5.0-SNAPSHOT.jar group3@cda.cefim-formation.org:petclinic.jar
            ssh group3@cda.cefim-formation.org 'java -jar petclinic.jar --server.port=8083'
