name: GitHub Actions Automatisation EC2 AWS
on: [push]
jobs:
  TestBuildAndGO:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code - test
        uses: actions/checkout@v2
      - run: mvn package
      
      
      #- name: build      
        #uses: actions/checkout@v2
      #- run: mvn package

      - name: deploy
        uses: shimataro/ssh-key-action@v2
        with:
            key: ${{ secrets.SSHPETCLINIC }}
            name: id_rsa # optional
            known_hosts: ${{ secrets.EC2_AWS }}
            if_key_exists: fail # replace / ignore / fail; optional (defaults to fail)
      - run: ssh-keyscan -H cda.cefim-formation.org >> ~/.ssh/known_hosts

      - name: blah    
        run: 
          scp ./target/spring-petclinic-2.5.0-SNAPSHOT.jar group3@cda.cefim-formation.org:petclinic.jar
          java -jar petclinic.jar --server.port=8083
