name: GitHub Actions Demo
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code - test
        uses: actions/checkout@v2
      - run: ./mvn package
      - run: echo ":desktop_computer: The workflow is now ready to test your code on the runner."
      
      #- name: build      
       # uses: actions/checkout@v2
      #- run: ./mvnw package

      #- name: deploy
       # uses: shimataro/ssh-key-action@v2
    #  with:
    #      key: ${{ secrets.SSH_CDA_PRIVATE_KEY }}
    #      name: id_rsa # optional
    #      known_hosts: ${{ secrets.CDA_EC2_HOST }}
    #      if_key_exists: fail # replace / ignore / fail; optional (defaults to fail)
    #- name: blah    
    #- run: 
    #    scp ./target/spring-petclinic-2.5.0-SNAPSHOT.jar ${{ secrets.CDA_EC2_HOST }}:petclinic.jar
    #    java -jar petclinic.jar --server.port=8083
